import unittest
from common.HTMLTestRunner import HTMLTestRunner
from testcase.test_register import TestRegister
from config.config import Config


def testsuite_register():
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestRegister))
    return suite


if __name__ == "__main__":
    s = testsuite_register()
    testreport_file = Config().base_path + '/testreport/HTMLReport.html'
    with open(testreport_file, 'w', encoding='utf8') as f:
        runner = HTMLTestRunner(
            stream=f,
            title='/api/register Test Report',
            description='generated by HTMLTestRunner.',
            verbosity=2
        )
        runner.run(s)
